name: rover_containers
services:
    mongo:
        container_name: mongodb
        network_mode: host
        ports:
            - 27017:27017
        image: mongo:4.0.13
    rover:
        container_name: rover_humble_jetson
        privileged: true
        network_mode: host
        group_add:
            - ${JTOP_GID}
        environment:
            - DISPLAY=unix$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=${XAUTH}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ${XAUTH}:${XAUTH}
            - /run/user/1000/at-spi:/run/user/1000/at-spi
            - /dev:/dev
            - ${PARENT_DIR}:/home/xplore/dev_ws/src
            - rover_humble_jetson_home_volume:/home/xplore
        image: ghcr.io/epflxplore/rover:humble-jetson
        command: /bin/bash -c "sudo chown -R $USERNAME:$USERNAME /home/$USERNAME; colcon
            build && tail -f /dev/null"
volumes:
    rover_humble_jetson_home_volume:
        external: true
        name: rover_humble_jetson_home_volume
